// A curated list of major US cities for dropdown selection.
// Replace/extend this list as needed or load from an external dataset.
const usCities: string[] = [
  "New York, NY",
  "Los Angeles, CA",
  "Chicago, IL",
  "Houston, TX",
  "Phoenix, AZ",
  "Philadelphia, PA",
  "San Antonio, TX",
  "San Diego, CA",
  "Dallas, TX",
  "San Jose, CA",
  "Austin, TX",
  "Jacksonville, FL",
  "Fort Worth, TX",
  "Columbus, OH",
  "Charlotte, NC",
  "San Francisco, CA",
  "Indianapolis, IN",
  "Seattle, WA",
  "Denver, CO",
  "Washington, DC",
  "Boston, MA",
  "El Paso, TX",
  "Nashville, TN",
  "Detroit, MI",
  "Oklahoma City, OK",
  "Portland, OR",
  "Las Vegas, NV",
  "Memphis, TN",
  "Louisville, KY",
  "Baltimore, MD",
  "Milwaukee, WI",
  "Albuquerque, NM",
  "Tucson, AZ",
  "Fresno, CA",
  "Mesa, AZ",
  "Sacramento, CA",
  "Kansas City, MO",
  "Atlanta, GA",
  "Long Beach, CA",
  "Omaha, NE",
  "Raleigh, NC",
  "Colorado Springs, CO",
  "Miami, FL",
  "Virginia Beach, VA",
  "Oakland, CA",
  "Minneapolis, MN",
  "Tulsa, OK",
  "Arlington, TX",
  "New Orleans, LA",
  "Wichita, KS",
  "Tampa, FL",
  "Aurora, CO",
  "Cleveland, OH",
  "Bakersfield, CA",
  "Anaheim, CA",
  "Honolulu, HI",
  "Riverside, CA",
  "Santa Ana, CA",
  "Corpus Christi, TX",
  "Lexington, KY",
  "Stockton, CA",
  "Henderson, NV",
  "St. Paul, MN",
  "St. Louis, MO",
  "Pittsburgh, PA",
  "Cincinnati, OH",
  "Anchorage, AK",
  "Greensboro, NC",
  "Plano, TX",
  "Lincoln, NE",
  "Orlando, FL",
  "Irvine, CA",
  "Newark, NJ",
  "Toledo, OH",
  "Durham, NC",
  "Chula Vista, CA",
  "Fort Wayne, IN",
  "Jersey City, NJ",
  "St. Petersburg, FL",
  "Laredo, TX",
  "Madison, WI",
  "Chandler, AZ",
  "Buffalo, NY",
  "Lubbock, TX",
  "Scottsdale, AZ",
  "Reno, NV",
  "Glendale, AZ",
  "Gilbert, AZ",
  "Baton Rouge, LA",
  "Boise, ID",
  "Richmond, VA",
  "Hialeah, FL",
  "Garland, TX",
  "Norfolk, VA",
  "Spokane, WA",
  "Chesapeake, VA",
  "Fremont, CA",
  "North Las Vegas, NV",
  "Irvine, CA",
  "San Bernardino, CA",
  "Birmingham, AL",
  "Rochester, NY",
  "Des Moines, IA",
  "Modesto, CA",
];

export default usCities;